apiVersion: v1
kind: Secret
metadata:
  name: feedback-smtp-secret
  namespace: saferoute
type: Opaque
stringData:
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_USERNAME: saferouteapp2025@gmail.com
  SMTP_PASSWORD: xgitgfhweneenfeo
  SYSTEM_FEEDBACK_TO_EMAIL: saferouteapp2025@gmail.com
