apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"redis","namespace":"saferoute"},"spec":{"ports":[{"port":6379,"protocol":"TCP","targetPort":6379}],"selector":{"app":"redis"},"type":"ClusterIP"}}
  creationTimestamp: "2026-02-26T13:18:54Z"
  name: redis
  namespace: saferoute
  resourceVersion: "771798"
  uid: ac2ec551-e8bf-4849-b8a7-cf629b911d5d
spec:
  clusterIP: 10.0.148.207
  clusterIPs:
  - 10.0.148.207
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
